configurations:
- url: "trojan://telegram-id-privatevpns@3.71.252.84:22222?security=tls&sni=trj.rollingnext.co.uk&type=tcp#M@M\
    \ \U0001F499"
- url: "trojan://telegram-id-directvpn@13.39.146.155:22222?security=tls&sni=trj.rollingnext.co.uk&type=tcp#M@M\
    \ \U0001F499"
- url: "vless://bfbd0da6-d36b-4e72-8868-96f2eb51b9e3@all.vpncustomize.website:2096?security=tls&sni=uGGkffkuygV2raykufukfkyKuyk-irancel-Mokhabera-Mamad-raitel-MIc.Snapp.monster&type=grpc&serviceName=@VPNCUSTOMIZE#M@M\
    \ \U0001F499"
- url: "vless://c688395a-b36b-4071-974b-bc91ac2ad2c4@986join.outline-vpn.cloud:443?security=tls&sni=edtunnel-b6t.pages.dev&type=ws&path=/&host=edtunnel-b6t.pages.dev#M@M\
    \ \U0001F499"
- url: "vless://884f9b2c-f0c5-44dd-a68e-3e39ce93bb39@cf-wkrs-pages-vless-aoy.pages.dev:443?security=tls&sni=cf-wkrs-pages-vless-aoy.pages.dev&type=ws&path=/?ed%3D2048&host=cf-wkrs-pages-vless-aoy.pages.dev#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkNTZmZDA0YS01ODAyLTQ3ODgtYmJhZi0zZWExNDE0MmU1OTc=@jp-03.feitucloud.com:10103#M@M\
    \ \U0001F499"
- url: "vless://d342d11e-d424-4583-b36e-524ab1f0afa4@12join.outline-vpn.cloud:2096?security=tls&sni=baipiao1.curly-train.pages.dev&type=ws&path=/?ed%3D2048&host=baipiao1.curly-train.pages.dev#M@M\
    \ \U0001F499"
- url: vmess://eyJhZGQiOiAiMzcuMTIwLjIwOS4xMjUiLCAiYWlkIjogIjY0IiwgImhvc3QiOiAiIiwgImlkIjogImRjMGNmMjJkLWUzNWMtNGI3Ny04OTI0LTk3N2Y2ODQ0OTA5YiIsICJuZXQiOiAidGNwIiwgInBhdGgiOiAiIiwgInBvcnQiOiAiNDk5ODIiLCAicHMiOiAiTUBNIFx1ZDgzZFx1ZGM5OVN0b2NraG9sbVN3ZWRlbiIsICJzY3kiOiAiYXV0byIsICJzbmkiOiAiIiwgInRscyI6ICIiLCAidHlwZSI6ICIiLCAidiI6ICIyIn0=
- url: "vless://884f9b2c-f0c5-44dd-a68e-3e39ce93bb39@542.outline-vpn.cloud:443?security=tls&sni=cf-wkrs-pages-vless-aoy.pages.dev&type=ws&path=/?ed%3D2048&host=cf-wkrs-pages-vless-aoy.pages.dev#M@M\
    \ \U0001F499"
- url: "vless://34de74d3-551a-4033-fc9c-fc36531b971a@104.31.16.65:2053?security=tls&sni=tel.RxV2ray.space&type=ws&path=/&host=tel.RxV2ray.space#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkNTZmZDA0YS01ODAyLTQ3ODgtYmJhZi0zZWExNDE0MmU1OTc=@ru-03.feitucloud.com:10103#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkNTZmZDA0YS01ODAyLTQ3ODgtYmJhZi0zZWExNDE0MmU1OTc=@ru-02.feitucloud.com:10102#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpkNTZmZDA0YS01ODAyLTQ3ODgtYmJhZi0zZWExNDE0MmU1OTc=@ru-04.feitucloud.com:10103#M@M\
    \ \U0001F499"
- url: vmess://eyJhZGQiOiAiNHM0LmFsbGFhbnNlbGwub25saW5lIiwgImFpZCI6ICIwIiwgImhvc3QiOiAidGVsZXdlYmlvbi5jb20iLCAiaWQiOiAiMGQ2YmE2NmYtM2I1MS00MzI1LTg0ZDAtNGQ5ZGQ1MzFmMGU5IiwgIm5ldCI6ICJ0Y3AiLCAicGF0aCI6ICIvIiwgInBvcnQiOiAiODQ0MyIsICJwcyI6ICJNQE0gXHVkODNkXHVkYzk5QXViZXJ2aWxsaWVyc0ZyYW5jZSIsICJzY3kiOiAiYXV0byIsICJzbmkiOiAiIiwgInRscyI6ICIiLCAidHlwZSI6ICJodHRwIiwgInYiOiAiMiJ9
- url: "vless://34de74d3-551a-4033-fc9c-fc36531b971a@95.179.213.70:2053?security=tls&sni=tel.RxV2ray.space&type=ws&path=/&host=tel.RxV2ray.space#M@M\
    \ \U0001F499"
- url: vmess://eyJhZGQiOiAiZGcxYWFhLnF3cWEubGluayIsICJhaWQiOiAiMCIsICJob3N0IjogImRnMWFhYS5xd3FhLmxpbmsiLCAiaWQiOiAiOWI4YjIyM2QtNmU5Ni00ODdmLWFkMmItZWFjNDhhNGNjMGEyIiwgIm5ldCI6ICJ3cyIsICJwYXRoIjogIi8iLCAicG9ydCI6ICI4MCIsICJwcyI6ICJNQE0gXHVkODNkXHVkYzk5VG9yb250b0NhbmFkYSIsICJzY3kiOiAiYXV0byIsICJzbmkiOiAiIiwgInRscyI6ICIiLCAidHlwZSI6ICIiLCAidiI6ICIyIn0=
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpHIXlCd1BXSDNWYW8=@185.172.113.182:810#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206VEV6amZBWXEySWp0dW9T@145.239.1.100:6679#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206cEtFVzhKUEJ5VFZUTHRN@51.77.53.200:4444#M@M \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp3NWRyQUw3UGZDSXdRMnljVXVvRHNWMkxz@212.113.106.243:13022#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206S2l4THZLendqZWtHMDBybQ==@54.36.174.181:8000#M@M \U0001F499"
- url: "ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@212.102.53.198:443#M@M \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpQMnp4WFBld2xWM0JsZnFxWWlTdGh2dExj@212.113.106.243:12949#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206WTZSOXBBdHZ4eHptR0M=@54.36.174.181:5000#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206S2l4THZLendqZWtHMDBybQ==@145.239.1.100:8080#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206cEtFVzhKUEJ5VFZUTHRN@ak1720.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou:4444#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp4a3VkNWhu@158.69.122.231:80#M@M \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpHIXlCd1BXSDNWYW8=@185.172.113.182:811#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprc2pmdXchc29wIw==@23.150.248.191:9098#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@23.92.127.134:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6YXNkS2thc2tKS2Zuc2E=@37.19.222.214:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@121.127.46.147:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6YXNkS2thc2tKS2Zuc2E=@143.244.58.102:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZG91Yi5pbw==@54.199.83.239:2333#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@193.182.144.240:989#M@M \U0001F499"
- url: "ss://YWVzLTEyOC1jZmI6c2hhZG93c29ja3M=@156.146.62.160:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@180.149.44.120:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@74.121.191.98:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@37.143.129.230:989#M@M \U0001F499"
- url: "ss://YWVzLTEyOC1jZmI6c2hhZG93c29ja3M=@156.146.38.163:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@213.169.137.221:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6YXNkS2thc2tKS2Zuc2E=@37.19.222.212:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@89.44.197.156:989#M@M \U0001F499"
- url: "vless://5f84c37f-f153-4abc-b634-859dc6bf90de@104.21.40.164:443?security=tls&sni=volatilizable.4kphotos.website&type=ws&path=/nimws&host=volatilizable.4kphotos.website#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@46.183.185.15:989#M@M \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTprc2pmdXchc29wIw==@69.50.95.251:9098#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@92.38.171.89:989#M@M \U0001F499"
- url: "ss://YWVzLTEyOC1jZmI6c2hhZG93c29ja3M=@109.201.152.181:443#M@M \U0001F499"
- url: "ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@212.102.53.80:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@5.188.226.187:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@5.188.6.8:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1nY206VmRhSXRLWW1GZg==@130.162.53.215:24576#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@51.15.27.48:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@77.72.5.113:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@77.72.5.150:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@185.90.61.153:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6YXNkS2thc2tKS2Zuc2E=@31.172.67.43:443#M@M \U0001F499"
- url: "vless://884f9b2c-f0c5-44dd-a68e-3e39ce93bb39@172.66.47.84:443?security=tls&sni=cf-wkrs-pages-vless-aoy.pages.dev&type=ws&path=/?ed%3D2048&host=cf-wkrs-pages-vless-aoy.pages.dev#M@M\
    \ \U0001F499"
- url: "ss://YWVzLTEyOC1nY206c2hhZG93c29ja3M=@212.102.53.78:443#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@185.180.12.81:989#M@M \U0001F499"
- url: "ss://YWVzLTI1Ni1jZmI6ZjhmN2FDemNQS2JzRjhwMw==@192.36.27.116:989#M@M \U0001F499"
- url: vmess://eyJhZGQiOiAiNjcuMjEuOTUuNzMiLCAiYWlkIjogIjY0IiwgImhvc3QiOiAiIiwgImlkIjogIjQxODA0OGFmLWEyOTMtNGI5OS05YjBjLTk4Y2EzNTgwZGQyNCIsICJuZXQiOiAidGNwIiwgInBhdGgiOiAiIiwgInBvcnQiOiAiNTMzMTQiLCAicHMiOiAiTUBNIFx1ZDgzZFx1ZGM5OUxvcyBBbmdlbGVzVW5pdGVkIFN0YXRlcyIsICJzY3kiOiAiYXV0byIsICJzbmkiOiAiIiwgInRscyI6ICIiLCAidHlwZSI6ICIiLCAidiI6ICIyIn0=
- url: vmess://eyJhZGQiOiAiMTQyLjQuMTI2LjI1IiwgImFpZCI6ICI2NCIsICJob3N0IjogIiIsICJpZCI6ICI0MTgwNDhhZi1hMjkzLTRiOTktOWIwYy05OGNhMzU4MGRkMjQiLCAibmV0IjogInRjcCIsICJwYXRoIjogIiIsICJwb3J0IjogIjUxNzE1IiwgInBzIjogIk1ATSBcdWQ4M2RcdWRjOTlTYW4gSm9zZVVuaXRlZCBTdGF0ZXMiLCAic2N5IjogImF1dG8iLCAic25pIjogIiIsICJ0bHMiOiAiIiwgInR5cGUiOiAiIiwgInYiOiAiMiJ9
- url: vmess://eyJhZGQiOiAiMTM3LjE3NS4yMi4xODciLCAiYWlkIjogIjY0IiwgImhvc3QiOiAiIiwgImlkIjogIjQxODA0OGFmLWEyOTMtNGI5OS05YjBjLTk4Y2EzNTgwZGQyNCIsICJuZXQiOiAidGNwIiwgInBhdGgiOiAiIiwgInBvcnQiOiAiNTM5OTkiLCAicHMiOiAiTUBNIFx1ZDgzZFx1ZGM5OVNhbiBKb3NlVW5pdGVkIFN0YXRlcyIsICJzY3kiOiAiYXV0byIsICJzbmkiOiAiIiwgInRscyI6ICIiLCAidHlwZSI6ICIiLCAidiI6ICIyIn0=
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpGbGp1c0dYYVdoZThtQUZhcXdvdHBP@51.141.11.19:39550#M@M\
    \ \U0001F499"
- url: vmess://eyJhZGQiOiAiMTU2LjIyNS42Ny40NyIsICJhaWQiOiAiNjQiLCAiaG9zdCI6ICIiLCAiaWQiOiAiM2NhOTEyZGEtNmFjMi00MThmLWI5Y2YtNDViNmY2OTQ1NzliIiwgIm5ldCI6ICJ0Y3AiLCAicGF0aCI6ICIiLCAicG9ydCI6ICI0OTIyNCIsICJwcyI6ICJNQE0gXHVkODNkXHVkYzk5V2FzaGluZ3RvblVuaXRlZCBTdGF0ZXMiLCAic2N5IjogImF1dG8iLCAic25pIjogIiIsICJ0bHMiOiAiIiwgInR5cGUiOiAiIiwgInYiOiAiMiJ9
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpqOE9WNXluRzZlcWdrQmpxMUU2YlFt@77.91.122.158:80#M@M\
    \ \U0001F499"
- url: "ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvYkt2OGx6c0xEbUVZU3BxNW1PaUo4@51.141.8.141:26031#M@M\
    \ \U0001F499"
- url: vmess://eyJhZGQiOiAiMTYyLjE1OS41OC4yMTgiLCAiYWlkIjogIjAiLCAiaG9zdCI6ICJubDEwZ2Jwcy42NTc3NjE3Lnh5eiIsICJpZCI6ICJjZDBjNTcwZi03NTdjLTQ4ZDItYTFiNi1jMDk0MDQzMWNjNDciLCAibmV0IjogIndzIiwgInBhdGgiOiAiLyIsICJwb3J0IjogIjgwIiwgInBzIjogIk1ATSBcdWQ4M2RcdWRjOTlUb3JvbnRvQ2FuYWRhIiwgInNjeSI6ICJhdXRvIiwgInNuaSI6ICIiLCAidGxzIjogIiIsICJ0eXBlIjogIiIsICJ2IjogIjIifQ==
